[connections.supabase]
SUPABASE_URL = "https://otzttzzotxkepwqdhsnr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90enR0enpvdHhrZXB3cWRoc25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA1OTAzOTQsImV4cCI6MjA0NjE2NjM5NH0.tD2MZCfdUmPxoMNN9i_y3WspqYkEqFZtmYUhpODCNfU"